exports.selectors = {
    homePage: '#homepage-wrapper',
    logInSignUpButton: "//*[@id='header-nav-collapse']/div/ul/li[6]/a",
    authenticateButton: '//*[@id="header-nav-collapse"]/div/ul/li[6]/a',
    myAccountDropDown: '//*[@id="header-nav-collapse"]/div/ul/li[6]/ul/li[7]/a',
    logInOrCreateAccountModal: '.modal-content',
    signUpTab: '/html/body/div[3]/div[2]/div/div/div[2]/div/ul/li[1]/a',
    logInTab: '/html/body/div[3]/div[2]/div/div/div[2]/div/ul/li[2]/a',
    logInEmailAddressField: '//*[@id="login[username]"]',
    logInPasswordField: '//*[@id="login[password]"]',
    logInButton: '#login-button',
    popularItemTiles: '.most-active>.tile-row>.tile',
    modalBody: '.modal-content',
    shoeSizeDropDown: '.sizes>.size-select-list',
    shoeSizeDropDownOptions: '.bonus-item',
    bidAskAmountTextField: '#amount',
    disabledBidAskAmountTextField: '.amount-no-input',
    bidBuyButton: '#market-summary > div.bid.bid-button-b > div.inner > div',
    bidModal: '#bid-create-form',
    askButton: '#market-summary > div.ask.ask-button-b > div.inner > div',
    askModalTitle: '#ask-modal-title',
    highestBidLowestAsktext: '.product-summary>.content>.market-info>span',
    sellNowTab: '.tab-selector>.tabs>.color-blue',
    continueToBidButton: '.btn-success',
    continueToAskButton: '#submit',
    iUnderstandBiddingButton: '.trade-info>div>.btn-understand',
    iUnderstandAskingButton: '.btn-understand',
    doppelgangerButton: '.btn-primary',
    warningText: '.warning-text',
    productSummary: '.product-summary',
    dialogSpinner: '#fb_dialog_loader_spinner'
}